### ISSUE TITLE
Running List for Front-end

### ISSUE THREAD

**Issue by sdl60660** [ksonda/global-river-runner#10]
General maintenance:
- [x] Unset yellow highlight on start run
- [x] Clicking "x" button while in overview mode should cancel the run
- [x] Pause then exit/cancel the run, then new run seems to cause state issues
- [ ] The "hitch"!! (caused by camera reaching first target point)

Compatibility Issues:
- [x] Sandwich feature occurrences not working correctly
- [x] Garbled linepath from the feature groups right now (squiggly blue lines)
- [x] Geocoder constrained to U.S. right now
- [x] Remove mapbounds
- [x] Remove flowrate options, since this won't be available elsewhere
- [x] Inset map needs to be dynamic
- [x] Remove U.S. boundaries on click handler
- [x] Tinker with inset map padding
- [x] Fix ocean bounds for stopping features
- [x] Add some sensible map zoom limits and prevent wrapping
- [x] Playback controls are hanging on a lot of international paths for some reason
- [x] Longer/less flowlines means smoothing coefficient should be lower and scale up more slowly at higher zoom levels
- [x] Non-ocean stopping features (remove Canada/Mexico, find dataset of global inland water bodies)
- [x] Parent feature stop points
- [x] Fix error handling on round re-attempt
- [x] Camera elevation calculation does not work at very high eleveations (e.g. himalayas) 
- [x] Add sensible error handling for unusable click values (e.g. Antarctica, the ocean)
- [x] Fix elevation sampling issue when 3D tiles aren't rendered on start (e.g. searching for start point that's not in map bounds)
- [x] Still having some sandwich or feature naming issues
- [x] Bound out Antarctica
- [x] Still having some zoom slider issues (see https://river-runner-global.vercel.app/?lng=127.05969032131696&lat=40.211533693233974)
- [x] Perceptual speed/terrain multiplier issue
- [x] flyTo to pre-render tiles, get correct elevation queries and smooth the flight to run transition
- [x] Name suggestion modal
- [x] Sub in NLDI/Firebase VAA for clicks in contiguous US (stitch together with Mexico/Canada results from last point, if necessary?)
- [x] Edit attribution blurb
- [x] Update README
- [x] Linked Coordinate to Flight/Start Elevation disjointedness is a lot better, but still not great for things like Everest, this has to be fixed
- [x] Great Salt Lake issue (hanging feature at end)
- [x] Fix Great Lakes
- [x] Manual override on the Saint Lawrence to replace the stopping feature with "Gulf of Saint Lawrence" or something while maintaining the existing stopping feature for the inland mapping?
- [x] Cut out unnecessary properties on requests
- [ ] Alter async pattern to start grabbing path data during initial tile render flight
- [ ] Variable smoothing based on flowline coordinate density?
- [ ] Fix inset map issues on change in path + varying quality from highlighted feature to main path or min zoom level

**Comment by sdl60660** [comment]
https://river-runner-lvetss2l6-samlearner.vercel.app/

**Comment by ksonda** [comment]
options for inland water bodies:

* https://www.hydrosheds.org/page/hydrolakes
* https://www.naturalearthdata.com/downloads/10m-physical-vectors/10m-lakes/

**Comment by sdl60660** [comment]
@ksonda these could work! if I want to mimic some of the ocean segmenting globally (e.g. segment out the mediterranean or the black sea, specifically, rather than labeling them as "Atlantic Ocean"), are you aware of any kind of ocean boundary dataset?

**Comment by dblodgett-usgs** [comment]
Marine labels? https://www.naturalearthdata.com/downloads/10m-physical-vectors/10m-physical-labels/

**Comment by sdl60660** [comment]
@dblodgett-usgs this is perfect, link is dead for some reason and had to find a cached version here: https://github.com/nvkelso/natural-earth-vector/tree/master/10m_physical, but this will take care of exactly what I need
