### ISSUE TITLE
attribution blurb

### ISSUE THREAD

**Issue by ksonda** [ksonda/global-river-runner#11]
This issue is for @dblodgett-usgs and I and @webb-ben to come up with what we want in the attribution blurb, or else documented somewhere linked from Sam's app.

First go:

Visualization by Sam Learner. Code and data for this project lives here (repo link).  Raindrop flowpaths are calculated using an API(link to pygeoapi process swagger), developed by Ben Webb(link) and Kyle Onda(link) from the Internet of Water project at Duke University(link), implemented as an OGC - API Process (link) in pygeoapi (link). The underlying data is based on MERIT-Hydro(link), with a simplification and processing algorithm (link to code/sciencebase) implemented by Dave Blodegett (link) at USGS, in accordance with the HY_features river Mainstems (link to pub) concept.

**Comment by sdl60660** [comment]
@ksonda that looks great, a couple of things:

1. Could you just paste in all of the associated links here?
2. We'll need a much-shortened version for mobile (needs to all fit on one line). There's basically space for about ten words max, maybe 15-20 if we stretch it to two lines. My suggestion would be either getting your names in there plus a single data link or adding a little UI popup thing for more details. Here's what the current version looks like
<img width="292" alt="Screen Shot 2021-09-22 at 2 36 32 PM" src="https://user-images.githubusercontent.com/12772904/134402070-9a17441d-ba73-4a11-9faf-a7e04b91c9de.png">
le

**Comment by ksonda** [comment]
We can set up a github.io page for this project that would then say and link all that stuff

**Comment by webb-ben** [comment]
Added some links while I took a break from code. They might be wrong!! Don't trust me

Visualization by Sam Learner. Code and data for this project lives [here](https://github.com/ksonda/global-river-runner). Raindrop flowpaths are calculated using an [API](https://merit.internetofwater.dev/openapi?f=html#/river-runner/executeRiver-runnerJob), developed by [Ben Webb](https://github.com/webb-ben) and Kyle Onda (link) from the [Internet of Water](https://internetofwater.org/) project at Duke University, implemented as an [OGC - API Process](https://ogcapi.ogc.org/processes/) in [pygeoapi](https://pygeoapi.io/). The underlying data is based on MERIT-Hydro (link), with a simplification and processing algorithm (link) implemented by Dave Blodegett (link) at USGS, in accordance with the HY_features river Mainstems (link to pub) concept.

**Comment by ksonda** [comment]
I have started a bigger blurb that can just be linked from the rive-runner little thing.

https://github.com/ksonda/global-river-runner/blob/gh-pages/index.md (available for now from https://ksonda.github.io/global-river-runner) I'm open to getting a snazzy domain though. 

This way I think the attribution blurb can just go something like..

```
Visualization by Sam Learner | twitter link | email link | github link

Sources: The data used in this project comes from the River Runner API, which is based on several open source projects and datasets. Learn about it [here](https://github.com/ksonda/global-river-runner/blob/gh-pages/index.md )
```
