### ISSUE TITLE
final source data

### ISSUE THREAD

**Issue by ksonda** [ksonda/global-river-runner#12]
- [x] @dblodgett-usgs @sdl60660 decide on appropriate level of simplification
- [x] @dblodgett-usgs decide and indicate final data location. hydroshare geoconnex folder is probably not it
- [x] @ksonda @webb-ben figure out CI/CD for local dev/Duke DB
- [x] @dblodgett-usgs automate production of .sql and placement in final data location (rather than or in addition to .gpkg)
- [x] @ksonda @webb-ben figure out CI/CD for production

**Comment by dblodgett-usgs** [comment]
Final data location. 
https://www.sciencebase.gov/catalog/item/614a8864d34e0df5fb97572d

**Comment by sdl60660** [comment]
@dblodgett-usgs in terms of simplification, is the trade-off for lower simplification just data size/initial processing time? would there be a response time tradeoff as well?

**Comment by dblodgett-usgs** [comment]
That's a good question. I would expect the response time to be similar.
