### ISSUE TITLE
Allegheny River is misclassified as Ohio River

### ISSUE THREAD

**Issue by sdl60660** [ksonda/global-river-runner#29]
**Describe the data problem**
The Allegheny River seems to be misclassified as the Ohio River for its entirety. Initially noticed near Pittsburgh, but the problem seems to persist upstream.

**To Reproduce**
https://river-runner-global.samlearner.com/?lng=-79.58416909772211&lat=40.70967444720185

**Suggested fix**
Allegheny River should be disaggregated from the Ohio. This is probably symptomatic of something larger, but I'm not in a position to say what.

**Evidence (optional)**
https://en.wikipedia.org/wiki/Allegheny_River

**Comment by dblodgett-usgs** [comment]
You are right --- I think this is something a bit bigger.

**Comment by dblodgett-usgs** [comment]
Sorry this took so long... I think I got this now.
![image](https://user-images.githubusercontent.com/1492803/151685151-c531d0ba-68a9-4925-8a9a-29d519b0b6d7.png)

**Comment by ksonda** [comment]
This is fixed
